### ISSUE TITLE
Contribution for the official godot docs

### ISSUE THREAD

**Issue by pwab** [dploeger/godot-migrationnotes#2]
Nice work! Would you like to contribute your migrationnotes to the godot docs? There is an [open issue](https://github.com/godotengine/godot-docs/issues/537) for that.

**Comment by dploeger** [comment]
Definitely, but I don't think, I can provide the complete tutorial, because I only scratched the surface of Godot until now. So, please use these notes as a basis for the tutorial, but I don't think, I could provide something useful.
