### ISSUE TITLE
Spatial and InputEvent changes

### ISSUE THREAD

**Issue by swenner** [dploeger/godot-migrationnotes#4]
Great document!
Three more additions:

- Spatial::look_at_from_pos(pos, target, up) was renamed to look_at_from_position(pos, target, up)
- InputEvent::type was removed. "is InputEventKey", "is InputEventMouseMotion" ect. should be used.
- InputEventMouseMotion::pos -> InputEventMouseMotion::postion

**Comment by dploeger** [comment]
Integrated. Thanks!
